name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push (latest)
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: golaoji/wecom-dev-audit:latest

    -
      # Push the new tag
      name: Build and Push New Tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: golaoji/wecom-dev-audit:${{ github.ref_name }}
